server:
  port: 8086

spring:
  application:
    name: Account-Service
  datasource:
    url:  jdbc:mysql://localhost:3306/accountservices
    username: root
    password: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8088
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

