server:
  port: 8085

spring:
  application:
    name: Customer-Service
  datasource:
    url: jdbc:mysql://localhost:3306/customerservices
    username: root
    password: admin

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8088


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
